name: Deploy Development

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          port: ${{ secrets.DROPLET_PORT }}
          script: |
            cd /root/31mp/healthline
            git fetch origin dev
            git checkout dev
            git reset --hard origin/dev
            pnpm install
            pnpm build
            pm2 restart TMP-COMPRO-DEV
